### ISSUE TITLE
Regarding the pretrained checkpoint

### ISSUE THREAD

**Issue by sreeharshaparuchur1** [facebookresearch/soundspaces-challenge#11]
Hi @SAGNIKMJR ,

To study the given nearTarget checkpoint for the active-source-separation challenge, I followed the evaluation-specific instructions at [challenge branch](https://github.com/SAGNIKMJR/active-AV-dynamic-separation/tree/challenge). On completing evaluation, I observed a disparity in the metrics that I obtained contrasted to that given in the AAViDSS paper and the baseline on the EvalAI webpage. I have verified that I am using the versions of libraries and Habitat mentioned in the repository. 

The paper reports values "in terms of mean separation quality of the dynamic monaural target over all T steps, averaged over 1,000 test episodes", to this extent, I compare the value of "MonoFromMem STFT L2 Loss over all time steps" for the STFT metric and the "MonoFromMem SI-SDR Mean" for the SI-SDR metric from the checkpoints with what is given in the paper.

The paper reports an SI-SDR value of **3.93** and an STFT value of **0.273** in the "Heard" setting. It also reports an SI-SDR value of **2.57** and an STFT value of **0.318** in the "Unheard" setting. 

I observed the following values: 
STFT: 0.297, SI-SDR: 3.725 in the "Heard" setting.
STFT: 0.326, SI-SDR: 2.242 in the "Unheard" setting.

These values are not consistent with the SI-SDR score obtained by the "baseline" on the EvalAI webpage. It would be helpful if you could share what changes were made to the baseline model compared to the checkpoint linked to on GitHub. The paper does mention that the metrics were computed using three different random seeds but such a gap does not seem likely to be caused by a different seed.

Lastly, there is a large difference in the dataset size between Move2Hear and AAViDSS with the inclusion of more scenes and more episodes. It would be appreciated if you could shed some light onto what made this possible.

If possible, kindly share the Move2Hear checkpoint retrained for this task as well.

Thank you

**Comment by SAGNIKMJR** [comment]
I reran the model on the challenge test set and got SI-SDR of 3.678 on heard and 3.731 on unheard. The datasets are different from the ones in the paper, so please don't compare with the numbers in the paper.

Are you sure you are using the right checkpoint and splits? Checkpoint link: https://utexas.box.com/shared/static/7jaww6xew54zv1llmfskhsiyuh3lddqx.zip, dataset link: https://utexas.box.com/shared/static/m1095s7xm9vvl0u6krcbww4aps646gzg.zip
