### ISSUE TITLE
How to convert the downloaded matterport3D data into data that can be used by soundspace? 

### ISSUE THREAD

**Issue by yyf17** [facebookresearch/soundspaces-challenge#2]
How to convert the downloaded matterport3D data into data that can be used by soundspace? For example, a scene of matterport3D I downloaded is 17DRP5sb8fy. The downloaded data is as shown in the figure. 

![image](https://user-images.githubusercontent.com/34536352/111105702-7e8dbb00-858e-11eb-960c-575a33ac6bc3.png)

How to convert it into the scene data 17DRP5sb8fy under soundspace [scene data path: data/scene_datasets/mp3d/17DRP5sb8fy/] as shown in the figure:
![image](https://user-images.githubusercontent.com/34536352/111105622-5e5dfc00-858e-11eb-9e78-634de165f0e4.png)

**Comment by ChanganVR** [comment]
@yyf17 did you specify the task type to be habitat? you should run the script like this:

`python download_mp.py --task habitat -o data/scene_datasets/mp3d/`

**Comment by yyf17** [comment]
@ChanganVR Thank you. 
I used the following cmd:
```
 python scripts/download_mp.py -o /mnt/yyf/data/matterport3D 
```
I didn't specified the task,Thank you.
