### ISSUE TITLE
I cannot find val_mini.json.gz

### ISSUE THREAD

**Issue by yyf17** [facebookresearch/soundspaces-challenge#4]
docker can run after carefully read your instruction.I cannot find val_mini.json.gz when I run the following cmd:
```
./test_locally_audionav_rgbd.sh --docker-name audionav_submission 

```
FileNotFoundError: [Errno 2] No such file or directory: 'data/datasets/audionav/mp3d/v1/val_mini/val_mini.json.gz'
![image](https://user-images.githubusercontent.com/34536352/111905063-d17edb00-8a84-11eb-9fe5-f3c5cb620708.png)

**Comment by ChanganVR** [comment]
val_mini.json.gz is contained in the dataset file in the [data](https://github.com/facebookresearch/sound-spaces/tree/master/soundspaces) page.

Use this command to downloaded the updated dataset file
`wget http://dl.fbaipublicfiles.com/SoundSpaces/datasets.tar.xz && tar xvf datasets.tar.xz`

**Comment by yyf17** [comment]
@ChanganVR Thanks
