### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by ShunqiM** [facebookresearch/soundspaces-challenge#5]
It is specified in README that we should clone the challenge repository by
`git clone https://github.com/changanvr/soundspaces-challenge.git `

However, it seems that the repository is private that I cannot access it.
Should I clone this repository instead?

**Comment by SAGNIKMJR** [comment]
Yeah, you need to clone this repo. Thanks for noticing the error. Updated the README with the correct link. Closing the issue.
