### ISSUE TITLE
Test Standard Phase

### ISSUE THREAD

**Issue by ShunqiM** [facebookresearch/soundspaces-challenge#6]
> Minival phase: This split is same as the one used in `./test_locally_audionav_rgbd.sh`

For the minival phase, I can follow the command provided in the shell script.
What config file should I use to run the experiment for the test-std phase?

**Comment by SAGNIKMJR** [comment]
You need to change `DATASET.SPLIT` in **configs/challenge_audionav.local.rgbd.yaml** to **test_multiple_unheard** for the test-std phase. I will make this more explicit in the README.
