### ISSUE TITLE
Need MapNavEnv for avwan_agent

### ISSUE THREAD

**Issue by ShunqiM** [facebookresearch/soundspaces-challenge#8]
Not sure what I'm missing here, but I cannot evaluate my checkpoints using the `avwan_agent.py` due to the lack of the mapper sensors (while I can evaluate ckpts without any issue by using the SoundSpace code).

  It seems that the `Challenge2022()` class is inheriting from the `Benchmark` class, which [uses the default configuration from av_nav](https://github.com/facebookresearch/sound-spaces/blob/0e87180459a5c9901bd1b17fe83405ebe57b9360/soundspaces/benchmark.py#L21), where sensors like "EgoMap" are not defined. 

However, even if I import the `get_task_config` from the av_wan folder, the Challenge is using a [basic habitat environment](https://github.com/facebookresearch/sound-spaces/blob/0e87180459a5c9901bd1b17fe83405ebe57b9360/soundspaces/benchmark.py#L41), whereas the map sensors need to be updated with [MapNavEnv class](https://github.com/facebookresearch/sound-spaces/blob/0e87180459a5c9901bd1b17fe83405ebe57b9360/ss_baselines/av_wan/mapnav_env.py#L89). In this case, the program stops complaining about undefined sensors, but the map sensors only returns the zero values by default.

I'm not really familiar with how the environments are defined so the above are just my guess of the problem, I guess there should be an easier solution for my issue but I can't figure it out myself.

**Comment by SAGNIKMJR** [comment]
Sorry for the late reply, but I somehow missed this issue.

I would suggest taking a look at the original SoundSpaces repo and using that to evaluate your av_wan agent. For uploading to the challenge, you can add a few lines to your eval code where you dump a dictionary into a json that has a structure similar to what we are expecting.

**Comment by ShunqiM** [comment]
Thanks, I will close this issue after I managed to do that.

**Comment by SAGNIKMJR** [comment]
Just a note: even though we don't provide the avwan performance as a baseline, we would recommend that you don't use the avwan results as a submission since it's already a published model. You can always improve upon avwan and submit it though.

**Comment by ShunqiM** [comment]
Sure, that's what I'm doing currently (integrating my methods onto avwan).
BTW, since I've emailed Changan but haven't got a reply. It seems I cannot reproduce the multiple sound spl using the wan method. I've evaluated the wan pre-trained weights provided, resulting in a 0.41 spl as reported. However, for my own reproduction, I can only get test spl around 0.34 by changing the split in the config file "train_with_am" to from "train_telephone" to "train_multiple" and leaving other hyper-parameters unchanged. Is there anything that should be changed in the configuration to improve the performance of the wan method for the unheard sound setting? Or what do you think could be wrong that prevents me from training a good avwan model?

**Comment by SAGNIKMJR** [comment]
Changan will try to get back to you on this soon.

**Comment by ShunqiM** [comment]
I've managed to generate JSON of a similar format, thanks for your help.
