### ISSUE TITLE
Dataset for the Active Audio-Visual Sound Separation Track

### ISSUE THREAD

**Issue by sreeharshaparuchur1** [facebookresearch/soundspaces-challenge#9]
Hi @SAGNIKMJR ,

The soundspaces-challenge repo says that the evaluation split for the AAViSS track is ```testUnheard_1000episodes```, however, on downloading the dataset specific splits, I do not find a folder specifying a split with that name. I seek this clarification as I'd like to know if the task will involve source separation in the near-target or far-target setting as well as getting to know the number of 'distractor' sounds in the testing environment.

Thank you

**Comment by SAGNIKMJR** [comment]
As mentioned in the README of the challenge, you need to download the AAViSS datasets from the `challenge` branch of https://github.com/SAGNIKMJR/active-AV-dynamic-separation

**Comment by sreeharshaparuchur1** [comment]
Apologies for the confusion, it arose due to a technical difficulty. I see that according to the splits, the testing environment has 2 sources (of which one is the distractor) and the task setting is ```nearTarget```
